apiVersion: v1
entries:
  haproxy:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 2.5.0
    created: "2022-01-04T16:01:23.529451811+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: HAProxy is a TCP proxy and a HTTP reverse proxy. It supports SSL
      termination and offloading, TCP and HTTP normalization, traffic regulation,
      caching and protection against DDoS attacks.
    digest: 92cc18087148c24716a032d95e1920028d131490761e0c1651c31d9252b004d1
    home: https://www.haproxy.org/
    keywords:
    - haproxy
    - proxy
    - infrastructure
    - robobee
    maintainers:
    - email: erwin@muellerpublic.de
      name: Erwin MÃ¼ller
    name: haproxy
    sources:
    - https://github.com/robobee-repos/helm-charts
    - https://github.com/haproxytech/haproxy
    urls:
    - haproxy-1.0.0.tgz
    version: 1.0.0
generated: "2022-01-04T16:01:23.526367827+01:00"
